# Copyright (c) 2020 Red Hat, Inc.
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "application.fullname" . }}
  labels:
    app: {{ template "application.name" . }}
    chart: {{ template "application.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "application.name" . }}
    helm.sh/chart: {{ template "application.chart" . }}
    component: clusterrolebinding
subjects:
- kind: ServiceAccount
  name: {{ template "application.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "application.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
